2018-04-19 17:03:00,187 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 17:08:29,493 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 17:23:57,707 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 17:25:07,141 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:00:59,372 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:02:04,372 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:02:04,713 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:07:14,302 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:07:53,683 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:08:53,267 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:11:44,418 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 18:12:35,611 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 19:13:29,657 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 19:32:43,540 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 19:32:43,904 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 19:47:12,631 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 19:47:12,987 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 19:47:30,085 INFO: microblog startup [in app\__init__.py:30]
2018-04-19 20:09:58,677 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:09:59,035 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:21:12,323 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:23:30,407 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:24:59,470 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:25:45,247 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:42:27,229 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:46:35,582 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 20:47:06,740 INFO: microblog startup [in app\__init__.py:30]
2018-04-19 21:14:34,667 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:14:35,003 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:16:17,627 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:17:00,213 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:18:22,029 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:19:36,447 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:20:19,259 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:20:54,605 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:21:25,305 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:21:58,605 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:21:58,927 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:24:49,571 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:27:16,263 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:27:41,678 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:28:14,835 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:28:50,000 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:29:07,836 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:29:50,582 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:31:16,801 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:31:44,441 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:33:36,812 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:37:05,220 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:42:54,051 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:43:29,267 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:45:27,414 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:46:50,453 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-19 21:50:08,993 INFO: microblog startup [in app\__init__.py:30]
2018-04-20 11:00:15,944 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 11:00:16,273 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 11:00:50,418 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 11:11:17,657 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 11:11:17,973 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 11:11:36,390 INFO: microblog startup [in app\__init__.py:30]
2018-04-20 11:13:56,543 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 11:13:56,859 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:27:50,257 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:28:18,946 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:32:29,391 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:33:26,596 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:34:36,713 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:36:05,549 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:37:37,509 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:38:38,125 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 15:39:45,690 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:43:20,355 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:43:36,137 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:45:40,385 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:47:49,739 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:50:18,822 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:51:50,796 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:53:57,993 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:54:16,882 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:55:43,599 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:56:05,773 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:57:26,548 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:57:49,838 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:58:47,980 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:58:59,076 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:58:59,414 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 16:59:52,234 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:00:32,907 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:01:12,431 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:01:28,010 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:02:08,677 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:02:20,226 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:03:56,424 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:04:09,921 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:08:27,269 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:08:27,595 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:09:38,578 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:09:38,911 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 17:10:00,892 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 20:26:40,200 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 20:43:25,713 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 21:45:30,681 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-20 21:45:31,032 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 10:29:03,688 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 10:29:04,030 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 10:31:49,351 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 10:35:50,229 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 10:36:12,413 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 17:59:13,055 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 17:59:13,401 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 18:57:39,592 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 18:57:45,052 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-21 18:57:45,411 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-23 19:32:05,953 INFO: microblog startup [in app\__init__.py:30]
2018-04-24 14:23:55,542 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-24 14:23:55,857 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-24 14:26:29,757 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-24 14:27:32,033 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:30]
2018-04-24 16:24:00,394 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:31]
2018-04-24 16:24:09,469 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:31]
2018-04-24 16:24:30,506 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:32]
2018-04-24 16:24:38,510 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:33]
2018-04-24 16:24:58,561 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:34]
2018-04-24 16:25:14,211 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:35]
2018-04-24 16:25:24,306 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:29:33,542 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:30:22,092 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:30:47,572 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:33:12,871 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:33:54,911 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:35:18,381 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:35:18,713 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:35:53,051 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:36:29,767 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:36:59,763 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:38:54,628 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:40:11,571 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:40:22,897 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:41:07,844 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:51:23,868 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:51:36,345 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:51:58,733 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:54:29,433 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:57:05,503 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:58:14,697 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 16:59:14,227 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:15:11,414 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:17:51,773 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:17:52,118 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:18:40,793 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:19:56,951 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:20:16,022 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:22:54,107 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:24:11,213 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:26:27,539 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:26:43,278 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:27:25,112 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:28:17,789 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:28:32,434 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:29:06,789 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:31:46,615 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 17:33:13,033 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:01:49,421 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:12:25,700 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:13:17,243 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:13:17,571 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:14:38,026 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:16:02,940 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:17:15,454 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:20:31,960 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:21:08,704 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 18:21:28,973 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:34:28,582 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:34:28,917 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:38:10,017 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:41:11,897 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:42:41,877 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:44:13,407 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:44:47,990 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:46:22,493 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 19:46:56,875 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:00:07,753 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:00:22,405 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:00:32,631 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:01:29,921 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:02:47,799 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:03:24,276 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:03:49,134 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:04:18,048 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:04:36,104 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:04:57,404 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:05:27,319 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:06:11,539 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:06:25,089 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:07:23,341 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:27:42,006 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 20:27:54,444 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 21:06:29,628 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-24 21:45:49,970 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-26 16:15:19,973 INFO: microblog startup [in app\__init__.py:36]
2018-04-26 16:31:26,332 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-26 16:31:34,319 INFO: microblog startup [in app\__init__.py:36]
2018-04-26 18:10:42,022 INFO: microblog startup [in app\__init__.py:36]
2018-04-26 19:32:13,062 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-26 19:32:13,398 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-26 20:34:05,993 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-26 20:34:06,329 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:27:52,680 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:27:53,063 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:30:56,431 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:37:03,289 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:40:59,273 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:42:51,298 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:42:53,730 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:42:54,095 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:43:31,637 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:43:32,000 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:45:05,219 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:45:05,579 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:45:42,171 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:47:07,691 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:47:51,946 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:48:06,997 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:48:07,375 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:48:13,644 ERROR: Exception on /content [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 22, in content
    AllContent = User.query.filter_by(username=user.username).first().posts.all()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2737, in all
    return list(self)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\dynamic.py", line 247, in __iter__
    return iter(self._clone(sess))
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: post.content [SQL: u'SELECT post.id AS post_id, post.content AS post_content, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.title AS post_title \nFROM post \nWHERE ? = post.user_id'] [parameters: (1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-04-28 10:48:28,936 ERROR: Exception on /content [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 22, in content
    AllContent = User.query.filter_by(username=user.username).first().posts.all()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2737, in all
    return list(self)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\dynamic.py", line 247, in __iter__
    return iter(self._clone(sess))
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: post.content [SQL: u'SELECT post.id AS post_id, post.content AS post_content, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.title AS post_title \nFROM post \nWHERE ? = post.user_id'] [parameters: (1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-04-28 10:48:40,137 ERROR: Exception on /content [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 22, in content
    AllContent = User.query.filter_by(username=user.username).first().posts.all()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2737, in all
    return list(self)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\dynamic.py", line 247, in __iter__
    return iter(self._clone(sess))
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: post.content [SQL: u'SELECT post.id AS post_id, post.content AS post_content, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.title AS post_title \nFROM post \nWHERE ? = post.user_id'] [parameters: (1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-04-28 10:49:16,026 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:49:18,049 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:49:18,897 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:49:20,443 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:49:22,224 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:49:22,726 ERROR: Exception on /content [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 22, in content
    AllContent = User.query.filter_by(username=user.username).first().posts.all()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2737, in all
    return list(self)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\dynamic.py", line 247, in __iter__
    return iter(self._clone(sess))
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: post.content [SQL: u'SELECT post.id AS post_id, post.content AS post_content, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.title AS post_title \nFROM post \nWHERE ? = post.user_id'] [parameters: (1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-04-28 10:49:24,184 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:49:52,848 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:49:53,194 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:50:03,242 ERROR: Exception on /user/eason [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 106, in user
    print(user)
IOError: [Errno 22] Invalid argument
2018-04-28 10:50:03,276 ERROR: Exception on /content [GET] [in C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\admin\PycharmProjects\name\app\views.py", line 22, in content
    AllContent = User.query.filter_by(username=user.username).first().posts.all()
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2737, in all
    return list(self)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\dynamic.py", line 247, in __iter__
    return iter(self._clone(sess))
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\admin\PycharmProjects\name\venv\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: post.content [SQL: u'SELECT post.id AS post_id, post.content AS post_content, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.title AS post_title \nFROM post \nWHERE ? = post.user_id'] [parameters: (1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-04-28 10:51:39,519 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:51:52,961 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:52:56,522 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:52:58,994 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 10:52:59,358 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:01:57,009 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:04:46,316 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:07:48,812 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:54:31,440 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:55:56,167 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:56:59,240 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 11:59:17,502 INFO: microblog startup [in app\__init__.py:36]
2018-04-28 12:03:53,869 INFO: microblog startup [in app\__init__.py:36]
2018-04-28 21:19:04,069 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:19:04,427 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:19:34,894 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:48:18,003 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:48:38,134 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:48:38,516 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:50:10,489 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:50:28,279 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:52:56,427 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:53:18,644 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:55:55,687 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:55:59,423 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:56:33,240 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 21:59:10,290 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-28 22:02:27,483 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 15:23:18,845 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 18:57:32,401 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 19:36:05,094 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 19:43:38,038 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:19:14,532 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:23:23,911 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:24:23,973 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:25:07,878 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:26:00,200 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:31:02,973 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:31:35,029 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:32:15,173 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
2018-04-29 20:32:15,523 INFO: microblog startup [in C:\Users\admin\PycharmProjects\name\app\__init__.py:36]
